name: Run Ansible Playbook via WSL

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  ansible-playbook:
    runs-on: windows-2019

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Enable WSL
      - name: Enable WSL
        run: |
          dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
        shell: powershell

      # Step 3: Install Ubuntu (WSL 1)
      - name: Install Ubuntu
        run: |
          Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile Ubuntu.appx
          Add-AppxPackage -Path .\Ubuntu.appx
          # Start WSL session to initialize Ubuntu
          wsl -d Ubuntu-18.04 -- echo "Ubuntu installed"
        shell: powershell

      # Step 4: Install Ansible in WSL
      - name: Install Ansible in WSL
        run: |
          wsl -d Ubuntu-18.04 -- sudo apt update
          wsl -d Ubuntu-18.04 -- sudo apt install -y ansible
        shell: bash

      # Step 5: Run Ansible Playbook in WSL
      - name: Run Ansible Playbook
        run: |
          # Copy playbook and inventory to WSL
          wsl -d Ubuntu-18.04 -- mkdir -p /home/ubuntu/repo
          cp -r $GITHUB_WORKSPACE/* /mnt/c/home/ubuntu/repo
          
          # Run the playbook inside WSL
          wsl -d Ubuntu-18.04 -- ansible-playbook /home/ubuntu/repo/path/to/your_playbook.yml -i /home/ubuntu/repo/path/to/inventory
        shell: bash

      # Step 6: Run PowerShell Module (within Ansible Playbook)
      - name: Run PowerShell Module (within Ansible Playbook)
        run: |
          Write-Output "PowerShell command execution handled by Ansible playbook tasks."
        shell: powershell
