name: Run Ansible Playbook via WSL

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  ansible-playbook:
    runs-on: windows-2019

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Enable WSL and install Ubuntu
      - name: Enable WSL and Install Ubuntu
        run: |
          dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
          Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1804 -OutFile Ubuntu.appx
          Add-AppxPackage .\Ubuntu.appx
          Start-Sleep -Seconds 10
          ubuntu config --default-user root
        shell: powershell

      # Step 3: Install Ansible in WSL
      - name: Install Ansible in WSL
        run: |
          wsl sudo apt update
          wsl sudo apt install -y ansible
        shell: bash

      # Step 4: Run Ansible Playbook in WSL
      - name: Run Ansible Playbook
        run: |
          # Copy playbook and inventory to WSL
          wsl cp -r $GITHUB_WORKSPACE /home/ubuntu/repo
          
          # Run the playbook inside WSL
          wsl ansible-playbook /home/ubuntu/repo/path/to/your_playbook.yml -i /home/ubuntu/repo/path/to/inventory
        shell: bash

      # Step 5: Execute PowerShell Module within the Playbook
      - name: Run PowerShell Module (within Ansible Playbook)
        # Assuming the playbook contains a task to run PowerShell commands on the Windows host.
        run: |
          Write-Output "PowerShell command execution will be handled by Ansible playbook tasks."
        shell: powershell
